apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: api-gateway-https
  namespace: {{.Release.Namespace}}
  annotations: 
    {{ tpl .Values.ingress.annotations . | nindent 4 | trim }}
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    #Routed Service recives HTTPS connections
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - http: 
      paths:
      - pathType: Prefix
        path: /
        backend: 
          service: 
            name: "api-gateway"
            port:
              number: 443
    host: {{ .Values.domain }}