{{ range $instance := .Values.services.awsConnector.instances }}
{{ $instanceID := $instance.connectorID | replace "aws." "" }}
apiVersion: v1
kind: Service
metadata:
  name: aws-connector-{{ $instanceID }}
  namespace: {{ $.Release.Namespace}}
spec:
  selector:
    app: aws-connector
  type: ClusterIP
  ports:
  - name: http
    port: 8085
    targetPort: 8085
    protocol: TCP
---
{{- end -}}