apiVersion: apps/v1
kind: Deployment
metadata:  
  name: device-manager
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: device-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-manager
  template:
    metadata:
      labels:
        app: device-manager
    spec:
      containers:
        - name: device-manager
          image: {{ .Values.services.deviceManager.image }}
          imagePullPolicy: Always
          tty: true         
          volumeMounts:
            - name: api-config
              mountPath: /etc/lamassuiot/config.yml
              subPath: config
          ports:
            - containerPort: 8085
      restartPolicy: Always
      volumes:
        - name: api-config
          configMap:  
            name: device-manager-config

