apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: downstream-tls-certificate
  namespace: {{.Release.Namespace}}
spec:
  isCA: false
  commonName: {{.Values.ingress.hostname}}
  duration: {{.Values.tls.certManagerOptions.duration}}
  dnsNames:
    - {{.Values.ingress.hostname}}
  secretName: downstream-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    {{ if ne .Values.tls.certManagerOptions.clusterIssuer "" }}
    kind: ClusterIssuer
    name: {{ .Values.tls.certManagerOptions.clusterIssuer }}
    {{ else }}
    kind: Issuer
    name:  {{ ternary .Values.tls.certManagerOptions.issuer "downstream-ca-selfsigned-issuer" (ne .Values.tls.certManagerOptions.issuer "") }}
    {{ end }}
    group: cert-manager.io