apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-downstream-cert
  namespace: {{.Release.Namespace}}
spec:
  isCA: true
  duration: {{.Values.tls.duration}}
  commonName: "downstream-selfsigned-cert"
  secretName: root-downstream-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io