postgres:
  hostname: "postgresql"
  port: 5432
  username: "admin"
  password: "admin"

amqp:
  hostname: "rabbitmq"
  port: 5672
  username: "admin"
  password: "admin"
  tls: false
services:
  keycloak:
    enabled: true
    image: ghcr.io/lamassuiot/keycloak:2.1.0
    adminCreds:
      username: "admin"
      password: "admin"
auth:
  oidc:
    frontend:
      authority: https://ci.lamassu.io/auth/realms/lamassu
ingress:
  enabled: true
  domain: ci.lamassu.io
  annotations: |
    kubernetes.io/ingress.class: "public"
  