postgres:
  hostname: "postgresql"
  port: 5432
  username: "admin"
  password: "admin"

amqp:
  hostname: "rabbitmq"
  port: 5672
  username: "admin"
  password: "admin"
  
services:
  services:
    ca:
      cryptoEngines:
        defaultEngineID: fs-1
        engines:
          - id: fs-1
            type: filesystem
            storage_directory: /crypto/fs

auth:
  oidc:
    frontend:
      authority: https://ci.lamassu.io/auth/realms/lamassu

gateway:
  extraRouting:
    - path: /auth
      name: auth
      target:
        host: auth-keycloak
        port: 80  # If no sidecar is used
  ports:
    http: 80
    https: 443
  addresses:
    -