apiVersion: apps/v1
kind: StatefulSet
metadata:  
  name: {{ include "soft.fullname" . }}
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: {{ include "soft.fullname" . }}
spec:
  replicas: 1
  serviceName: {{ include "soft.fullname" . }}
  selector:
    matchLabels:
      app: {{ include "soft.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "soft.fullname" . }}
    spec:
      containers:
        - name: softhsm-v2
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5657
          env:
            - name: SLOT
              value: "0"
            - name: LABEL
              value: "{{ .Values.hsm.label }}"
            - name: PIN
              value: "{{ .Values.hsm.pin }}"
            - name: SO_PIN
              value: "{{ .Values.hsm.so_pin }}"
            - name: CONNECTION_PROTOCOL
              value: "tcp"
          volumeMounts:
            - name: softhsm-v2-data
              mountPath: /softhsm/tokens
            - name: pkcs11-tls-psk
              mountPath: /sym.psk
              subPath: key.psk
      restartPolicy: Always
      volumes:
        - name: pkcs11-tls-psk
          secret:
            secretName: "{{ include "soft.fullname" . }}-psk"
  volumeClaimTemplates:
  - metadata:
      name: softhsm-v2-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: null
      resources:
        requests:
          storage: 2Gi

