name: Fast lane Test

on: workflow_dispatch

jobs:
  fast-lane-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 ci.lamassu.io" | sudo tee -a /etc/hosts
      - uses: azure/setup-kubectl@v4.0.0
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.12.1
      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        with:
          config: .github/ci/kind.yaml
      - name: Prepare kind cluster
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.3/cert-manager.yaml
          kubectl apply --filename https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
          kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=180s
      - name: run fast lane
        run: |
          ./scripts/lamassu-fast-lane.sh -n -ns lamassu-ci -d ci.lamassu.io -p 30443 -l ./charts/lamassu
      - name: show info
        run: |
          kubectl get pods -n lamassu-ci
          kubectl get svc -n lamassu-ci
          kubectl get ingress -n lamassu-ci
      - name: Check if the app is running
        run: |
          sleep 3
          curl -s -o /dev/null -w "%{http_code}" -k https://ci.lamassu.io:30443
          curl -s -o /dev/null -w "%{http_code}" -k https://ci.lamassu.io:30443/auth/
      - name: Run helm tests
        run: |
          helm test -n lamassu-ci lamassu