name: Fast lane Test

on: workflow_dispatch

jobs:
  fast-lane-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 ci.lamassu.io" | sudo tee -a /etc/hosts
      - uses: azure/setup-kubectl@v4.0.0
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.12.1
      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        with:
          config: .github/ci/kind.yaml
      - name: Prepare kind cluster
        run: |
          helm install eg oci://docker.io/envoyproxy/gateway-helm --version v1.3.0 -n envoy-gateway-system --create-namespace -f .github/ci/eg.yaml --wait
          cat <<EOF | kubectl apply -f -
            apiVersion: gateway.networking.k8s.io/v1
            kind: GatewayClass
            metadata:
              name: eg
            spec:
              controllerName: gateway.envoyproxy.io/gatewayclass-controller
          EOF
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.3/cert-manager.yaml
      - name: run fast lane
        run: |
          ./scripts/lamassu-fast-lane.sh -n -ns lamassu-ci -d ci.lamassu.io -l ./charts/lamassu
      - name: show info
        run: |
          kubectl get pods -A
          kubectl get svc -A
          kubectl get gtw -A
      - name: Check if the app is running
        run: |
          curl -s -o /dev/null -w "%{http_code}" -k https://ci.lamassu.io:10443
          curl -s -o /dev/null -w "%{http_code}" -k https://ci.lamassu.io:10443/auth/
      - name: Run helm tests
        run: |
          helm test -n lamassu-ci lamassu